version: '3'
services:
  apollo:
    image: idoop/docker-apollo:1.3.0
    container_name: apollo
    network_mode: "host"
    restart: always
    volumes:
      - ./logs:/opt/logs
#   - ./application-ldap.yml:/apollo-portal/util/application-ldap.yml:ro #ldap配置文件挂载路径
#启动前,确认对应环境的数据库已经建立，否则apollo无法启动.
#默认端口:portal:8070; dev:8080,8090; fat:8081,8091; uat:8082,8092; pro:8083,8093
    environment:
      PORTAL_DB: jdbc:mysql://192.168.0.188:3306/apolloportaldb?characterEncoding=utf8
      PORTAL_DB_USER: apollo
      PORTAL_DB_PWD: bs_apollo@123
#     PORTAL_PORT: 80
#     PORTAL_LDAP: "TRUE"

      DEV_DB: jdbc:mysql://192.168.0.188:3306/apolloportaldb?characterEncoding=utf8
      DEV_DB_USER: apollo
      DEV_DB_PWD: bs_apollo@123

      FAT_DB: jdbc:mysql://192.168.0.188:3306/apolloconfigdb_fat?characterEncoding=utf8
      FAT_DB_USER: apollo
      FAT_DB_PWD: bs_apollo@123

#      PRO_DB: jdbc:mysql://192.168.0.188:3306/apolloconfigdb_pro?characterEncoding=utf8
#      PRO_DB_USER: apollo
#      PRO_DB_PWD: bs_apollo@123

